server {
  listen 80;
  listen [::]:80;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ { proxy_pass http://command-center-backend:8200/api/; }
  location = /index.html { add_header Cache-Control "no-store"; }
  location / { try_files $uri $uri/ /index.html; }
}
